using System.ComponentModel.DataAnnotations;

namespace EI.API.Service.Rest.Helpers.Model;

public abstract class BaseDto
{
    /// <summary>
    ///   The primary identifier of this entity. May only be <c>null</c> upon record creation,
    ///   in which case it is generated by the API implementation prior to creating the persistent record.
    /// </summary>
    public Guid? Id { get; set; }

    /// <summary>
    ///   The name of the user who is creating or modifying the record.
    ///   The API implementation is generally responsible for setting this based on the authenticated user
    ///   that is invoking the API.
    /// </summary>
    [MaxLength(120)]
    public string? UpdatedBy { get; set; }

    /// <summary>
    ///   Record timestamp for the record, used for protecting against concurrent updates to the
    ///   underlying record. This is generated by the API implementation, and when attempting updates to
    ///   the record, must be provided to ensure that the record has not been updated since the last read.
    /// </summary>
    public byte[]? RowVersion { get; set; }
}