using System.ComponentModel.DataAnnotations;

namespace EI.API.Service.Rest.Helpers.Model;

/// <summary>
///   Base class that provides common properties for DTOs with Culture-aware translations.
/// </summary>
public abstract class BaseTranslationDto : BaseDto
{
    /// <summary>
    ///   Specifies the culture code for the user-displayable text properties of this result.
    ///   Matches the actual result, which may be the default culture if the requested culture is not available.
    /// </summary>
    [Required, MaxLength(20)]
    public string? CultureCode { get; set; }

    /// <summary>
    ///   Specifies the name of the user who last updated the translations.
    ///   May differ from the user who last updated the non-translated properties.
    /// </summary>
    // Map tracking info from the translation table into the DTO
    [MaxLength(120)]
    public string? TranslationUpdatedBy { get; set; }

    /// <summary>
    ///   Record timestamp for the translations, used for protecting against concurrent updates to the 
    ///   underlying record.  This is generated by the API implementation, and when attempting updates to
    ///   the record, must be provided to ensure that the record has not been updated since the last read.
    /// </summary>
    public byte[]? TranslationRowVersion { get; set; }
}